# .project metadata for Falco
# Documentation: https://github.com/cncf/automation/tree/main/utilities/dot-project

# TODO: Add package_managers if distributed via registries

schema_version: "1.0.0"
slug: "falco"
name: "Falco"
description: "Falco, the cloud-native runtime security project, is the de facto Kubernetes threat detection engine"
type: "project"
project_lead: "andreagit97" # TODO: AUTO-DETECTED — please verify
slack_channels: # TODO: AUTO-DETECTED — please verify the channel(s) below
  - name: "#falco"
    link: "https://kubernetes.slack.com/messages/falco"
    primary: true
  - name: "#slack-channel"
  - name: "#sandbox"

maturity_log:
  - phase: "graduated"
    date: "2018-10-10T00:00:00Z"
    issue: "https://github.com/cncf/toc/pull/956" # TODO: AUTO-DETECTED — please verify

repositories: # TODO: AUTO-DETECTED primary — please verify
  - url: "https://github.com/falcosecurity/falco"
    primary: true
    # tags: [core, sig-apps] # Optional

website: "https://falco.org/"

artwork: "https://landscape.cncf.io/logos/falco.svg"

adopters:
  path: "https://github.com/falcosecurity/falco/blob/master/ADOPTERS.md"


# TODO: Add package manager identifiers if your project is distributed via registries
# package_managers:
#   docker: "falcosecurity/falco"

social:
  twitter: "https://twitter.com/falco_org"

security:
  policy:
    path: "https://github.com/falcosecurity/.github/blob/main/SECURITY.md"
  contact:
    advisory_url: "https://github.com/falcosecurity/falco/security/advisories/new"

governance:
  contributing:
    path: "https://github.com/falcosecurity/falco/blob/master/Contributing.md"
  code_of_conduct:
    path: "https://github.com/falcosecurity/.github/blob/main/CODE_OF_CONDUCT.md"

legal:
  license:
    path: "https://github.com/falcosecurity/falco/blob/master/LICENSE"
  identity_type:
    has_dco: true # AUTO-DETECTED — please verify
    has_cla: false # AUTO-DETECTED — please verify
    dco_url:
      path: "https://developercertificate.org/"

documentation:
  readme:
    path: "https://github.com/falcosecurity/falco/blob/master/README.md"

landscape:
  category: "Provisioning"
  subcategory: "Security & Compliance"

# CLOMonitor Score: 84/100
# Documentation: 100 | License: 86 | Best Practices: 62 | Security: 68
